sudo: required
services:
  - docker
  
  before_install:
    - docker build -t codenutridocker/docker-react -f Dockerfile.dev .

    script:
      - docker run codenutridocker/docker-react npm run test -- --coverage
